{
  "openapi": "3.0.1",
  "info": {
    "title": "Iriks-IT API",
    "description": "Here comes the documentation of the api for  [Iriks-IT](https://api.iriks-it.nl)",
    "termsOfService": "https://iriks-it.nl/api-terms/",
    "contact": {
      "email": "devop@iriks.it",
      "name": "Matthijs Iriks",
      "url": "https://iriks-it.nl/"
    },
    "x-logo": {
      "url": "https://iriks-it.nl/logo.png",
      "backgroundColor": "#FFFFFF",
      "altText": "Iriks-IT Logo"
    },
    "version": "1.0.0"
  },
  "externalDocs": {
    "description": "Find out more about us here.",
    "url": "https://iriks-it.nl"
  },
  "servers": [
    {
      "url": "https://api.iriks-it.nl/v1"
    }
  ],
  "tags": [
    {
      "name": "account"
    },
    {
      "name": "basics"
    }
  ],
  "paths": {
    "/docs": {
      "get": {
        "tags": [
          "basics"
        ],
        "summary": "/docs",
        "description": "Need a link to the documentation ? here is the most up2date link.",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "success": true,
                      "error": false,
                      "code": 200,
                      "message": "documentation is available on https://docs.iriks-it.nl/"
                    }
                  },
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "error": {
                      "type": "boolean",
                      "default": false
                    },
                    "code": {
                      "type": "integer",
                      "default": 200,
                      "format": "int32"
                    },
                    "message": {
                      "type": "string",
                      "default": "documentation is available on https://docs.iriks-it.nl/"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "success": true,
                      "error": false,
                      "code": 200,
                      "message": "documentation is available on https://docs.iriks-it.nl/"
                    }
                  }
                }
              }
            },
            "headers": {
              "X-RateLimit-Limit": {
                "schema": {
                  "type": "integer",
                  "format": "int32",
                  "default": 25
                },
                "description": "Your total limit"
              },
              "X-RateLimit-Remaining": {
                "schema": {
                  "type": "integer",
                  "format": "int32",
                  "default": 24
                },
                "description": "Your calls remaining"
              },
              "X-RateLimit-Reset-In": {
                "schema": {
                  "type": "integer",
                  "format": "int32",
                  "default": 300
                },
                "description": "Your calls remaining will reset in x seconds"
              }
            }
          },
          "505": {
            "$ref": "#/components/responses/default505"
          }
        },
        "operationId": "get.basic.docs"
      }
    },
    "/help": {
      "get": {
        "tags": [
          "basics"
        ],
        "summary": "/help",
        "description": "Need a link to the documentation ? here is the most up2date link.",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "success": true,
                      "error": false,
                      "code": 200,
                      "message": "documentation is available on https://docs.iriks-it.nl/"
                    }
                  },
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "error": {
                      "type": "boolean",
                      "default": false
                    },
                    "code": {
                      "type": "integer",
                      "default": 200,
                      "format": "int32"
                    },
                    "message": {
                      "type": "string",
                      "default": "documentation is available on https://docs.iriks-it.nl/"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "success": true,
                      "error": false,
                      "code": 200,
                      "message": "documentation is available on https://docs.iriks-it.nl/"
                    }
                  }
                }
              }
            },
            "headers": {
              "X-RateLimit-Limit": {
                "schema": {
                  "type": "integer",
                  "format": "int32",
                  "default": 25
                },
                "description": "Your total limit"
              },
              "X-RateLimit-Remaining": {
                "schema": {
                  "type": "integer",
                  "format": "int32",
                  "default": 24
                },
                "description": "Your calls remaining"
              },
              "X-RateLimit-Reset-In": {
                "schema": {
                  "type": "integer",
                  "format": "int32",
                  "default": 300
                },
                "description": "Your calls remaining will reset in x seconds"
              }
            }
          },
          "505": {
            "$ref": "#/components/responses/default505"
          }
        },
        "operationId": "get.basic.help",
        "parameters": []
      }
    },
    "/auth/register": {
      "post": {
        "summary": "/auth/register",
        "operationId": "post.account.register",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "code": {
                      "type": "integer",
                      "default": 200,
                      "format": "int32"
                    },
                    "data": {
                      "type": "object",
                      "default": {
                        "token": "1|aqWx2RpjFTtYsaOVi3M8df6p54VLKW23W6f48a0",
                        "name": "Silvia"
                      }
                    },
                    "message": {
                      "type": "string",
                      "default": "User register successfully."
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Registration Error. email already in use!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": false
                    },
                    "code": {
                      "type": "integer",
                      "default": 409,
                      "format": "int32"
                    },
                    "data": {
                      "type": "string",
                      "default": "Account already exists, please choose a different one."
                    },
                    "message": {
                      "type": "string",
                      "default": "Registration Error."
                    }
                  }
                }
              }
            }
          },
          "406": {
            "$ref": "#/components/responses/default406"
          },
          "505": {
            "$ref": "#/components/responses/default505"
          }
        },
        "requestBody": {
          "$ref": "#/components/requestBodies/account.register"
        },
        "description": "Register your account here, you still need to verify this account when done.",
        "tags": [
          "account"
        ]
      }
    },
    "/auth/verify": {
      "post": {
        "summary": "/auth/verify",
        "operationId": "post.account.verify",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "code": {
                      "type": "integer",
                      "default": 200,
                      "format": "int32"
                    },
                    "data": {
                      "type": "object",
                      "default": "User verified successfully."
                    },
                    "message": {
                      "type": "string",
                      "default": "Validation Success."
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Validation Error, verify process only",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": false
                    },
                    "code": {
                      "type": "integer",
                      "default": 409,
                      "format": "int32"
                    },
                    "data": {
                      "type": "string",
                      "default": "Something bad broke, please contact: api@iriks-it.nl"
                    },
                    "message": {
                      "type": "string",
                      "default": "Validation Error."
                    }
                  }
                }
              }
            }
          },
          "406": {
            "$ref": "#/components/responses/default406"
          },
          "505": {
            "$ref": "#/components/responses/default505"
          }
        },
        "requestBody": {
          "$ref": "#/components/requestBodies/account.verify"
        },
        "description": "You found the verification code in your mail, now you can verify your account and start using it!",
        "tags": [
          "account"
        ]
      }
    },
    "/auth/login": {
      "post": {
        "summary": "/auth/login",
        "operationId": "post.account.login",
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "code": {
                      "type": "integer",
                      "default": 200,
                      "format": "int32"
                    },
                    "data": {
                      "type": "object",
                      "default": {
                        "token": "3|qF30ZVY2xW1OXJieMLXhUXZowwgVGVbm6F3kSoT714e04dec",
                        "expire": "2025-01-30 05:46:46",
                        "name": "Silvia"
                      }
                    },
                    "message": {
                      "type": "string",
                      "default": "Validation Success."
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Login Error, verify first!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": false
                    },
                    "code": {
                      "type": "integer",
                      "default": 409,
                      "format": "int32"
                    },
                    "data": {
                      "type": "string",
                      "default": "Account hasn't been verified yet, please verify this first!"
                    },
                    "message": {
                      "type": "string",
                      "default": "Unauthorised"
                    }
                  }
                }
              }
            }
          },
          "406": {
            "$ref": "#/components/responses/default406"
          },
          "505": {
            "$ref": "#/components/responses/default505"
          }
        },
        "requestBody": {
          "$ref": "#/components/requestBodies/account.login"
        },
        "description": "You want a Bearer Token? this is the way to get it!",
        "tags": [
          "account"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "account.register": {
        "required": [
          "name",
          "email",
          "password",
          "c_password"
        ],
        "properties": {
          "name": {
            "type": "string",
            "example": "Silvia"
          },
          "email": {
            "type": "string",
            "example": "silvia@iriks-it.nl"
          },
          "password": {
            "type": "string",
            "example": "g!v3m3f00dn0w!"
          },
          "c_password": {
            "type": "string",
            "example": "g!v3m3f00dn0w!"
          }
        },
        "xml": {
          "name": "Account register"
        }
      },
      "account.verify": {
        "required": [
          "email",
          "code"
        ],
        "properties": {
          "email": {
            "type": "string",
            "example": "silvia@iriks-it.nl"
          },
          "code": {
            "type": "string",
            "example": "1234-ABCD-5678-EDFG-1337"
          }
        },
        "xml": {
          "name": "Account verify"
        }
      },
      "account.login": {
        "required": [
          "email",
          "password"
        ],
        "properties": {
          "email": {
            "type": "string",
            "example": "silvia@iriks-it.nl"
          },
          "password": {
            "type": "string",
            "example": "g!v3m3f00dn0w!"
          }
        },
        "xml": {
          "name": "Account login"
        }
      }
    },
    "securitySchemes": {
      "iriksit_oauth2": {
        "type": "oauth2",
        "description": "This needs to be placed in the header, with the Bearer prefix.",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.iriks-it.nl/oath2/authorize.php",
            "refreshUrl": "https://api.iriks-it.nl/oath2/refresh.php",
            "scopes": {
              "basic-read": "allows read on basic flagged endpoints",
              "basic-write": "allows write on basic flagged endpoints",
              "wp_vulnerability-write": "allows write on basic flagged endpoints"
            }
          }
        }
      }
    },
    "requestBodies": {
      "account.register": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/account.register"
            }
          }
        }
      },
      "account.verify": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/account.verify"
            }
          }
        }
      },
      "account.login": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/account.login"
            }
          }
        }
      }
    },
    "responses": {
      "default401": {
        "description": "Unauthorized, insufficient scope",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "x-examples": {
                "example-1": {
                  "success": false,
                  "error": true,
                  "code": 401,
                  "message": "Unauthorized, insufficient scope"
                }
              },
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "error": {
                  "type": "boolean",
                  "default": true
                },
                "code": {
                  "type": "integer",
                  "default": 401,
                  "format": "int32"
                },
                "message": {
                  "type": "string",
                  "default": "Unauthorized, insufficient scope"
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "success": false,
                  "error": true,
                  "code": 401,
                  "message": "Unauthorized, insufficient scope"
                }
              }
            }
          }
        },
        "headers": {
          "X-RateLimit-Limit": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 25
            },
            "description": "Your total limit"
          },
          "X-RateLimit-Remaining": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 24
            },
            "description": "Your calls remaining"
          },
          "X-RateLimit-Reset-In": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 300
            },
            "description": "Your calls remaining will reset in x seconds"
          }
        }
      },
      "default404": {
        "description": "Command not found with current user credentials",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "x-examples": {
                "example-1": {
                  "success": false,
                  "error": true,
                  "code": 404,
                  "message": "Command not found with current user information"
                }
              },
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "error": {
                  "type": "boolean",
                  "default": true
                },
                "code": {
                  "type": "integer",
                  "default": 404,
                  "format": "int32"
                },
                "message": {
                  "type": "string",
                  "default": "Command not found with current user information"
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "success": false,
                  "error": true,
                  "code": 404,
                  "message": "Command not found with current user credentials"
                }
              }
            }
          }
        },
        "headers": {
          "X-RateLimit-Limit": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 25
            },
            "description": "Your total limit"
          },
          "X-RateLimit-Remaining": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 24
            },
            "description": "Your calls remaining"
          },
          "X-RateLimit-Reset-In": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 300
            },
            "description": "Your calls remaining will reset in x seconds"
          }
        }
      },
      "default406": {
        "description": "Validation Error, consult data object!",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "code": {
                  "type": "integer",
                  "default": 406,
                  "format": "int32"
                },
                "message": {
                  "type": "string",
                  "default": "Validation Error."
                },
                "data": {
                  "type": "object",
                  "default": {
                    "field1": "The field1 field is required.",
                    "field2": "The field2 field must match field1."
                  }
                }
              }
            }
          }
        },
        "headers": {
          "X-RateLimit-Limit": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 25
            },
            "description": "Your total limit"
          },
          "X-RateLimit-Remaining": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 24
            },
            "description": "Your calls remaining"
          },
          "X-RateLimit-Reset-In": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 300
            },
            "description": "Your calls remaining will reset in x seconds"
          }
        }
      },
      "default505": {
        "description": "Request was not send over HTTPS",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "x-examples": {
                "example-1": {
                  "success": false,
                  "error": true,
                  "code": 505,
                  "message": "Request was not send over HTTPS"
                }
              },
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "error": {
                  "type": "boolean",
                  "default": true
                },
                "code": {
                  "type": "integer",
                  "default": 505,
                  "format": "int32"
                },
                "message": {
                  "type": "string",
                  "default": "Request was not send over HTTPS"
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "success": false,
                  "error": true,
                  "code": 505,
                  "message": "Request was not send over HTTPS"
                }
              }
            }
          }
        },
        "headers": {
          "X-RateLimit-Limit": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 25
            },
            "description": "Your total limit"
          },
          "X-RateLimit-Remaining": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 24
            },
            "description": "Your calls remaining"
          },
          "X-RateLimit-Reset-In": {
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 300
            },
            "description": "Your calls remaining will reset in x seconds"
          }
        }
      }
    }
  }
}
